"""empty message

Revision ID: 23d9789c13ff
Revises: 826fb752b69e
Create Date: 2020-05-13 20:49:10.949304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d9789c13ff'
down_revision = '826fb752b69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.Column('artist_image_link', sa.String(length=500), nullable=True),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('start_time', 'venue_id', 'artist_id')
    )
    op.drop_table('joinTable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joinTable',
    sa.Column('Venue.id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Artist.id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Artist.id'], ['Artist.id'], name='joinTable_Artist.id_fkey'),
    sa.ForeignKeyConstraint(['Venue.id'], ['Venue.id'], name='joinTable_Venue.id_fkey'),
    sa.PrimaryKeyConstraint('Venue.id', 'Artist.id', 'start_time', 'artist_name', 'venue_name', name='joinTable_pkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
