"""empty message

Revision ID: 83205719c732
Revises: 9c51deb832c3
Create Date: 2020-05-12 03:01:18.691193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83205719c732'
down_revision = '9c51deb832c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('past_shows', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows')
    # ### end Alembic commands ###
