"""empty message

Revision ID: 8cd0379d07ea
Revises: f2ca50ff9ab5
Create Date: 2020-05-13 12:53:04.634041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd0379d07ea'
down_revision = 'f2ca50ff9ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    # ### end Alembic commands ###
